### ISSUE TITLE
004-Feature-Template-Chrome-Extension-Boiler-Plate

### ISSUE THREAD

**Issue by philemonputra** [Shyam-Sundar-Bharathi/cse210-fa24-group14#6]
# Feature-004: Template Chrome Extension-Boiler-Plate

## Description
Create a simple skeleton template for the Chrome extension.
Follow the link below for guidance.
https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world

**Comment by shouhardik** [comment]
This contains the boiler code for the Chrome Extension to allow developers to take context-specific notes directly on any website. Added features like create & delete using JavaScript.
