### ISSUE TITLE
005-Feature-Unit-E2E-Testing-Setup-Playwright

### ISSUE THREAD

**Issue by rashi-bhansali** [Shyam-Sundar-Bharathi/cse210-fa24-group14#8]
- Create an initial Chrome Extension : **Hello World - Test Extension** (`index.html`, `index.js` , `styles.css`, `manifest.json`
- Install Playwright `npm install -D playwright`
- Setup `playwright.config.js` to detect unit tests and e2e tests in the code base and disallow for headless testing (since we're building a Chrome extension)
- Write basic unit test : `tests/index.test.js`
- Write basic e2e test: `e2e/index.e2e.test.js`
- Run these tests: `npx playwright test --project=unit` & `npx playwright test --project=e2e`

**Comment by MitchelHsu** [comment]
Solved by PR #9
